/**
 * Generate and download a PDF trip summary.
 * Uses a hidden iframe with print-optimized HTML.
 */
export function exportTripPDF({ trip, events, children }) {
  const driverName = trip.drivers?.full_name || 'Unknown Driver'
  const routeName = trip.routes?.name || 'Trip'
  const schoolName = trip.routes?.school_name || ''
  const startTime = trip.started_at ? new Date(trip.started_at).toLocaleString('en-ZA') : '—'
  const endTime = trip.ended_at ? new Date(trip.ended_at).toLocaleString('en-ZA') : 'In progress'
  const tripType = trip.trip_type === 'morning' ? 'Morning' : 'Afternoon'
  const dateStr = trip.started_at ? new Date(trip.started_at).toLocaleDateString('en-ZA', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) : ''

  const eventRows = (events || []).map(e => {
    const time = e.created_at ? new Date(e.created_at).toLocaleTimeString('en-ZA', { hour: '2-digit', minute: '2-digit' }) : ''
    const type = e.event_type.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    const notes = e.notes ? ` — ${e.notes}` : ''
    return `<tr><td style="padding:6px 12px;border-bottom:1px solid #eee;font-size:13px;">${time}</td><td style="padding:6px 12px;border-bottom:1px solid #eee;font-size:13px;">${type}${notes}</td></tr>`
  }).join('')

  const childList = (children || []).map(c => c.full_name).join(', ') || 'N/A'

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>Trip Summary — ${routeName}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a2e; margin: 0; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; border-bottom: 2px solid #00C566; padding-bottom: 16px; }
    .logo { font-size: 20px; font-weight: 800; color: #00C566; }
    .subtitle { font-size: 12px; color: #6b7280; margin-top: 2px; }
    .date { font-size: 13px; color: #6b7280; text-align: right; }
    .section { margin-bottom: 24px; }
    .section-title { font-size: 14px; font-weight: 700; color: #00C566; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .field-label { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
    .field-value { font-size: 14px; font-weight: 600; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; padding: 8px 12px; background: #f5f5f7; font-size: 11px; text-transform: uppercase; color: #6b7280; letter-spacing: 0.5px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo">SafeRide Kids</div>
      <div class="subtitle">Trip Summary Report</div>
    </div>
    <div class="date">${dateStr}</div>
  </div>

  <div class="section">
    <div class="section-title">Trip Details</div>
    <div class="grid">
      <div><div class="field-label">Route</div><div class="field-value">${routeName}</div></div>
      <div><div class="field-label">Type</div><div class="field-value">${tripType} Trip</div></div>
      <div><div class="field-label">Driver</div><div class="field-value">${driverName}</div></div>
      <div><div class="field-label">School</div><div class="field-value">${schoolName}</div></div>
      <div><div class="field-label">Started</div><div class="field-value">${startTime}</div></div>
      <div><div class="field-label">Ended</div><div class="field-value">${endTime}</div></div>
      <div><div class="field-label">Status</div><div class="field-value">${trip.status}</div></div>
      <div><div class="field-label">Children</div><div class="field-value">${childList}</div></div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Trip Events (${events?.length || 0})</div>
    ${events?.length ? `
    <table>
      <thead><tr><th>Time</th><th>Event</th></tr></thead>
      <tbody>${eventRows}</tbody>
    </table>` : '<p style="font-size:13px;color:#6b7280;">No events recorded for this trip.</p>'}
  </div>

  <div class="footer">
    Generated by SafeRide Kids &middot; KelyRa Tech (Pty) Ltd &middot; ${new Date().toLocaleDateString('en-ZA')}
  </div>
</body>
</html>`

  // Open in new window and trigger print (saves as PDF)
  const printWindow = window.open('', '_blank', 'width=800,height=600')
  if (!printWindow) return false
  printWindow.document.write(html)
  printWindow.document.close()
  printWindow.onload = () => {
    printWindow.print()
  }
  return true
}
